use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let root = manifest_dir.join("../..");
    let content = root.join("content");
    let mut paths = BTreeSet::new();

    for entry in fs::read_dir(&content).expect("read content directory") {
        let path = entry.expect("read content entry").path();
        if path.is_dir() {
            collect_references(&path, &mut paths);
        }
    }
    println!("cargo:rerun-if-changed={}", content.display());
    for path in &paths {
        let source = root.join(path);
        if !source.is_file() {
            panic!("cb-file source does not exist or is not a file: {path}");
        }
        if fs::read_to_string(&source).is_err() {
            panic!("cb-file source is not valid UTF-8: {path}");
        }
        println!("cargo:rerun-if-changed={}", source.display());
    }

    let mut generated = String::from("// @generated by build.rs — do not edit.\n");
    generated.push_str("pub const EMBEDDED_FILE_PATHS: &[&str] = &[\n");
    for path in &paths {
        generated.push_str(&format!("    {path:?},\n"));
    }
    generated.push_str(
        "];\n\npub fn embedded_file(path: &str) -> Option<&'static str> {\n    match path {\n",
    );
    for path in &paths {
        let absolute = root
            .join(path)
            .canonicalize()
            .unwrap_or_else(|_| root.join(path));
        generated.push_str(&format!(
            "        {path:?} => Some(include_str!({absolute:?})),\n"
        ));
    }
    generated.push_str("        _ => None,\n    }\n}\n");

    let output =
        PathBuf::from(env::var("OUT_DIR").expect("output directory")).join("embedded_file_apps.rs");
    fs::write(output, generated).expect("write embedded cb-file registry");
}

fn collect_references(dir: &Path, paths: &mut BTreeSet<String>) {
    for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("read {}: {e}", dir.display())) {
        let entry = entry.unwrap_or_else(|e| panic!("read entry in {}: {e}", dir.display()));
        let path = entry.path();
        if path.is_dir() {
            collect_references(&path, paths);
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("md") {
            continue;
        }
        let markdown =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        for raw in cb_file_paths(&markdown) {
            paths.insert(normalize_path(raw));
        }
    }
}

fn cb_file_paths(markdown: &str) -> Vec<&str> {
    let mut paths = Vec::new();
    let mut remaining = markdown;
    while let Some(start) = remaining.find("<cb-file") {
        remaining = &remaining[start..];
        let Some(end) = remaining.find('>') else {
            panic!("unterminated <cb-file> tag");
        };
        let tag = &remaining[..=end];
        let path = quoted_attribute(tag, "path")
            .unwrap_or_else(|| panic!("<cb-file> is missing a quoted path attribute"));
        paths.push(path);
        remaining = &remaining[end + 1..];
    }
    paths
}

fn quoted_attribute<'a>(tag: &'a str, wanted: &str) -> Option<&'a str> {
    let mut rest = tag.strip_prefix("<cb-file")?;
    loop {
        rest = rest.trim_start();
        if rest.is_empty() || rest.starts_with('>') || rest.starts_with("/>") {
            return None;
        }
        let key_end = rest.find(|c: char| !(c.is_ascii_alphanumeric() || c == '-' || c == '_'))?;
        let key = &rest[..key_end];
        rest = rest[key_end..].trim_start();
        if !rest.starts_with('=') {
            return None;
        }
        rest = rest[1..].trim_start();
        let quote = rest.chars().next()?;
        if quote != '\'' && quote != '"' {
            return None;
        }
        rest = &rest[quote.len_utf8()..];
        let value_end = rest.find(quote)?;
        let value = &rest[..value_end];
        rest = &rest[value_end + quote.len_utf8()..];
        if key == wanted {
            return Some(value);
        }
    }
}

fn normalize_path(raw: &str) -> String {
    let path = raw.trim().trim_start_matches("./");
    if path.is_empty()
        || path.starts_with('/')
        || path
            .split('/')
            .any(|part| part.is_empty() || part == "." || part == "..")
    {
        panic!("cb-file path must be a repository-relative file without traversal: {raw:?}");
    }
    path.to_owned()
}
